# https://skaffold.dev/docs/references/yaml/
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: redis-ha-tester
build:
  artifacts:
  - image: redis-ha-tester
    ko:
      fromImage: alpine #golang:1.17-alpine
      dir: src/cmd/app
      dependencies:
        paths:
        - "src/*"
        - "skaffold/*"
        - "skaffold.yaml"
        ignore: []
deploy:
  kubectl:
    manifests:
      - skaffold/app.yaml
portForward:
  - resourceType: service
    resourceName: redis-ha-tester
    port: 8080
    address: 127.0.0.1
    localPort: 8080
