---
apiVersion: v1
kind: Service
metadata:
  name: redis-ha-tester
spec:
  type: ClusterIP
  selector:
    app: redis-ha-tester
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ha-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ha-tester
  template:
    metadata:
      labels:
        app: redis-ha-tester
    spec:
      containers:
        - name: app
          image: redis-ha-tester
          resources: {}
          env:
            - name: LOG_LEVEL
              value: info
            - name: REDIS_CLUSTER_SERVICE_HOST
              value: "redis-cluster.redis-cluster.svc.cluster.local"
